### PR TITLE
Replace all casings for the different strings

### PR DESCRIPTION
**Pull request by lameox**
Avoids tricking the Extension by writing something like "cFC"

### CODE REVIEW

**Comment by wtfrank** [comment]
The reason I didn't use a case insensitive search was so that it would preserve reasonable capitalisation - I didn't want e.g. "The MBC Dunks Imperium Fleet" to become "The MBC Dunks the bee guys Fleet". How about capitalising the first letter if the first line of the matched text was capitalised?

**Comment by lameox** [comment]
This should do the Trick now

**Comment by lameox** [comment]
This should do the Trick

**Comment by wtfrank** [comment]
looks good

**Pull request merged**
